/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 08/07/2016 13:54:04
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            8000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_PLLCLKFreq_Value                     168000000
#define MX_SYSCLKFreq_VALUE                     168000000
#define MX_HCLKFreq_Value                       168000000
#define MX_FCLKCortexFreq_Value                 168000000
#define MX_CortexFreq_Value                     168000000
#define MX_AHBFreq_Value                        168000000
#define MX_APB1Freq_Value                       42000000
#define MX_APB2Freq_Value                       84000000
#define MX_APB1TimFreq_Value                    84000000
#define MX_APB2TimFreq_Value                    168000000
#define MX_48MHZClocksFreq_Value                48000000
#define MX_EthernetFreq_Value                   168000000
#define MX_I2SClocksFreq_Value                  96000000
#define MX_RTCFreq_Value                        32000
#define MX_WatchDogFreq_Value                   32000
#define MX_MCO1PinFreq_Value                    16000000
#define MX_MCO2PinFreq_Value                    168000000

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- SDIO       --------------------------------*/

#define MX_SDIO                                 1

/* GPIO Configuration */

/* Pin PD2 */
#define MX_SDIO_CMD_Pin                         PD2
#define MX_SDIO_CMD_GPIO_AF                     GPIO_AF12_SDIO
#define MX_SDIO_CMD_GPIO_Speed_High_Default     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDIO_CMD_GPIO_PuPd                   GPIO_NOPULL
#define MX_SDIO_CMD_GPIOx                       GPIOD
#define MX_SDIO_CMD_GPIO_Mode                   GPIO_MODE_AF_PP
#define MX_SDIO_CMD_GPIO_Pin                    GPIO_PIN_2

/* Pin PC8 */
#define MX_SDIO_D0_Pin                          PC8
#define MX_SDIO_D0_GPIO_AF                      GPIO_AF12_SDIO
#define MX_SDIO_D0_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDIO_D0_GPIO_PuPd                    GPIO_NOPULL
#define MX_SDIO_D0_GPIOx                        GPIOC
#define MX_SDIO_D0_GPIO_Mode                    GPIO_MODE_AF_PP
#define MX_SDIO_D0_GPIO_Pin                     GPIO_PIN_8

/* Pin PC9 */
#define MX_SDIO_D1_Pin                          PC9
#define MX_SDIO_D1_GPIO_AF                      GPIO_AF12_SDIO
#define MX_SDIO_D1_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDIO_D1_GPIO_PuPd                    GPIO_NOPULL
#define MX_SDIO_D1_GPIOx                        GPIOC
#define MX_SDIO_D1_GPIO_Mode                    GPIO_MODE_AF_PP
#define MX_SDIO_D1_GPIO_Pin                     GPIO_PIN_9

/* Pin PC10 */
#define MX_SDIO_D2_Pin                          PC10
#define MX_SDIO_D2_GPIO_AF                      GPIO_AF12_SDIO
#define MX_SDIO_D2_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDIO_D2_GPIO_PuPd                    GPIO_NOPULL
#define MX_SDIO_D2_GPIOx                        GPIOC
#define MX_SDIO_D2_GPIO_Mode                    GPIO_MODE_AF_PP
#define MX_SDIO_D2_GPIO_Pin                     GPIO_PIN_10

/* Pin PC11 */
#define MX_SDIO_D3_Pin                          PC11
#define MX_SDIO_D3_GPIO_AF                      GPIO_AF12_SDIO
#define MX_SDIO_D3_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDIO_D3_GPIO_PuPd                    GPIO_NOPULL
#define MX_SDIO_D3_GPIOx                        GPIOC
#define MX_SDIO_D3_GPIO_Mode                    GPIO_MODE_AF_PP
#define MX_SDIO_D3_GPIO_Pin                     GPIO_PIN_11

/* Pin PC12 */
#define MX_SDIO_CK_Pin                          PC12
#define MX_SDIO_CK_GPIO_AF                      GPIO_AF12_SDIO
#define MX_SDIO_CK_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDIO_CK_GPIO_PuPd                    GPIO_NOPULL
#define MX_SDIO_CK_GPIOx                        GPIOC
#define MX_SDIO_CK_GPIO_Mode                    GPIO_MODE_AF_PP
#define MX_SDIO_CK_GPIO_Pin                     GPIO_PIN_12

/*-------------------------------- SPI2       --------------------------------*/

#define MX_SPI2                                 1

/* GPIO Configuration */

/* Pin PB15 */
#define MX_SPI2_MOSI_Pin                        PB15
#define MX_SPI2_MOSI_GPIO_AF                    GPIO_AF5_SPI2
#define MX_SPI2_MOSI_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI2_MOSI_GPIO_PuPd                  GPIO_NOPULL
#define MX_SPI2_MOSI_GPIOx                      GPIOB
#define MX_SPI2_MOSI_GPIO_Mode                  GPIO_MODE_AF_PP
#define MX_SPI2_MOSI_GPIO_Pin                   GPIO_PIN_15

/* Pin PB13 */
#define MX_SPI2_SCK_Pin                         PB13
#define MX_SPI2_SCK_GPIO_AF                     GPIO_AF5_SPI2
#define MX_SPI2_SCK_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI2_SCK_GPIO_PuPd                   GPIO_NOPULL
#define MX_SPI2_SCK_GPIOx                       GPIOB
#define MX_SPI2_SCK_GPIO_Mode                   GPIO_MODE_AF_PP
#define MX_SPI2_SCK_GPIO_Pin                    GPIO_PIN_13

/* Pin PB14 */
#define MX_SPI2_MISO_Pin                        PB14
#define MX_SPI2_MISO_GPIO_AF                    GPIO_AF5_SPI2
#define MX_SPI2_MISO_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI2_MISO_GPIO_PuPd                  GPIO_NOPULL
#define MX_SPI2_MISO_GPIOx                      GPIOB
#define MX_SPI2_MISO_GPIO_Mode                  GPIO_MODE_AF_PP
#define MX_SPI2_MISO_GPIO_Pin                   GPIO_PIN_14

/* Pin PB12 */
#define MX_SPI2_NSS_Pin                         PB12
#define MX_SPI2_NSS_GPIO_AF                     GPIO_AF5_SPI2
#define MX_SPI2_NSS_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI2_NSS_GPIO_PuPd                   GPIO_NOPULL
#define MX_SPI2_NSS_GPIOx                       GPIOB
#define MX_SPI2_NSS_GPIO_Mode                   GPIO_MODE_AF_PP
#define MX_SPI2_NSS_GPIO_Pin                    GPIO_PIN_12

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/*-------------------------------- USART1     --------------------------------*/

#define MX_USART1                               1

#define MX_USART1_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PA10 */
#define MX_USART1_RX_Pin                        PA10
#define MX_USART1_RX_GPIO_AF                    GPIO_AF7_USART1
#define MX_USART1_RX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART1_RX_GPIO_PuPd                  GPIO_PULLUP
#define MX_USART1_RX_GPIOx                      GPIOA
#define MX_USART1_RX_GPIO_Mode                  GPIO_MODE_AF_PP
#define MX_USART1_RX_GPIO_Pin                   GPIO_PIN_10

/* Pin PA9 */
#define MX_USART1_TX_Pin                        PA9
#define MX_USART1_TX_GPIO_AF                    GPIO_AF7_USART1
#define MX_USART1_TX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART1_TX_GPIO_PuPd                  GPIO_PULLUP
#define MX_USART1_TX_GPIOx                      GPIOA
#define MX_USART1_TX_GPIO_Mode                  GPIO_MODE_AF_PP
#define MX_USART1_TX_GPIO_Pin                   GPIO_PIN_9

/*-------------------------------- USB_OTG_FS --------------------------------*/

#define MX_USB_OTG_FS                           1

#define MX_USB_OTG_FS_DEVICE                    1

/* GPIO Configuration */

/* Pin PA11 */
#define MX_USB_OTG_FS_DM_Pin                    PA11
#define MX_USB_OTG_FS_DM_GPIO_AF                GPIO_AF10_OTG_FS
#define MX_USB_OTG_FS_DM_GPIO_Speed             GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USB_OTG_FS_DM_GPIO_PuPd              GPIO_NOPULL
#define MX_USB_OTG_FS_DM_GPIOx                  GPIOA
#define MX_USB_OTG_FS_DM_GPIO_Mode              GPIO_MODE_AF_PP
#define MX_USB_OTG_FS_DM_GPIO_Pin               GPIO_PIN_11

/* Pin PA12 */
#define MX_USB_OTG_FS_DP_Pin                    PA12
#define MX_USB_OTG_FS_DP_GPIO_AF                GPIO_AF10_OTG_FS
#define MX_USB_OTG_FS_DP_GPIO_Speed             GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USB_OTG_FS_DP_GPIO_PuPd              GPIO_NOPULL
#define MX_USB_OTG_FS_DP_GPIOx                  GPIOA
#define MX_USB_OTG_FS_DP_GPIO_Mode              GPIO_MODE_AF_PP
#define MX_USB_OTG_FS_DP_GPIO_Pin               GPIO_PIN_12

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PE3 */
#define MX_PE3_Pin                              PE3
#define MX_PE3_GPIO_PuPd                        GPIO_NOPULL
#define MX_PE3_GPIOx                            GPIOE
#define MX_PE3_GPIO_Mode                        GPIO_MODE_INPUT
#define MX_PE3_GPIO_Pin                         GPIO_PIN_3

/* Pin PA6 */
#define MX_PA6_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP
#define MX_PA6_Pin                              PA6
#define MX_PA6_PinState                         GPIO_PIN_RESET
#define MX_PA6_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PA6_GPIO_PuPd                        GPIO_NOPULL
#define MX_PA6_GPIOx                            GPIOA
#define MX_PA6_GPIO_Pin                         GPIO_PIN_6

/* Pin PE4 */
#define MX_PE4_Pin                              PE4
#define MX_PE4_GPIO_PuPd                        GPIO_NOPULL
#define MX_PE4_GPIOx                            GPIOE
#define MX_PE4_GPIO_Mode                        GPIO_MODE_INPUT
#define MX_PE4_GPIO_Pin                         GPIO_PIN_4

/* Pin PA7 */
#define MX_PA7_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP
#define MX_PA7_Pin                              PA7
#define MX_PA7_PinState                         GPIO_PIN_RESET
#define MX_PA7_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PA7_GPIO_PuPd                        GPIO_NOPULL
#define MX_PA7_GPIOx                            GPIOA
#define MX_PA7_GPIO_Pin                         GPIO_PIN_7

#endif  /* __MX_DEVICE_H */

